// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	Login_C2S
	Login_S2C
	RegisterName_C2S
	RegisterName_S2C
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Login_S2C_Code int32

const (
	Login_S2C_YES Login_S2C_Code = 0
	Login_S2C_NO  Login_S2C_Code = 1
)

var Login_S2C_Code_name = map[int32]string{
	0: "YES",
	1: "NO",
}
var Login_S2C_Code_value = map[string]int32{
	"YES": 0,
	"NO":  1,
}

func (x Login_S2C_Code) Enum() *Login_S2C_Code {
	p := new(Login_S2C_Code)
	*p = x
	return p
}
func (x Login_S2C_Code) String() string {
	return proto.EnumName(Login_S2C_Code_name, int32(x))
}
func (x *Login_S2C_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Login_S2C_Code_value, data, "Login_S2C_Code")
	if err != nil {
		return err
	}
	*x = Login_S2C_Code(value)
	return nil
}

type RegisterName_S2C_Code int32

const (
	RegisterName_S2C_YES RegisterName_S2C_Code = 0
	RegisterName_S2C_NO  RegisterName_S2C_Code = 3
)

var RegisterName_S2C_Code_name = map[int32]string{
	0: "YES",
	3: "NO",
}
var RegisterName_S2C_Code_value = map[string]int32{
	"YES": 0,
	"NO":  3,
}

func (x RegisterName_S2C_Code) Enum() *RegisterName_S2C_Code {
	p := new(RegisterName_S2C_Code)
	*p = x
	return p
}
func (x RegisterName_S2C_Code) String() string {
	return proto.EnumName(RegisterName_S2C_Code_name, int32(x))
}
func (x *RegisterName_S2C_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterName_S2C_Code_value, data, "RegisterName_S2C_Code")
	if err != nil {
		return err
	}
	*x = RegisterName_S2C_Code(value)
	return nil
}

type Login_C2S struct {
	Sdk              *string `protobuf:"bytes,1,opt,name=sdk" json:"sdk,omitempty"`
	Uid              *string `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Token            *string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login_C2S) Reset()         { *m = Login_C2S{} }
func (m *Login_C2S) String() string { return proto.CompactTextString(m) }
func (*Login_C2S) ProtoMessage()    {}

func (m *Login_C2S) GetSdk() string {
	if m != nil && m.Sdk != nil {
		return *m.Sdk
	}
	return ""
}

func (m *Login_C2S) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *Login_C2S) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type Login_S2C struct {
	Code             *Login_S2C_Code `protobuf:"varint,1,opt,name=code,enum=msg.Login_S2C_Code" json:"code,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Login_S2C) Reset()         { *m = Login_S2C{} }
func (m *Login_S2C) String() string { return proto.CompactTextString(m) }
func (*Login_S2C) ProtoMessage()    {}

func (m *Login_S2C) GetCode() Login_S2C_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Login_S2C_YES
}

type RegisterName_C2S struct {
	Nickname         *string `protobuf:"bytes,1,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterName_C2S) Reset()         { *m = RegisterName_C2S{} }
func (m *RegisterName_C2S) String() string { return proto.CompactTextString(m) }
func (*RegisterName_C2S) ProtoMessage()    {}

func (m *RegisterName_C2S) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type RegisterName_S2C struct {
	Code             *RegisterName_S2C_Code `protobuf:"varint,1,opt,name=code,enum=msg.RegisterName_S2C_Code" json:"code,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *RegisterName_S2C) Reset()         { *m = RegisterName_S2C{} }
func (m *RegisterName_S2C) String() string { return proto.CompactTextString(m) }
func (*RegisterName_S2C) ProtoMessage()    {}

func (m *RegisterName_S2C) GetCode() RegisterName_S2C_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return RegisterName_S2C_YES
}

func init() {
	proto.RegisterEnum("msg.Login_S2C_Code", Login_S2C_Code_name, Login_S2C_Code_value)
	proto.RegisterEnum("msg.RegisterName_S2C_Code", RegisterName_S2C_Code_name, RegisterName_S2C_Code_value)
}
